name 'choco-apps'
maintainer 'Todd Pigram'
maintainer_email 'todd@toddpigram.com'
license 'Apache 2.0'
description 'Installs/Configures choco-apps'
long_description 'Installs/Configures choco-apps'
version '0.1.8'

depends 'windows'
depends 'chocolatey'
